### ISSUE TITLE
Add ecommerce related layouts

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#116]
(Pull request: #118)

How it works: http://recordit.co/RcEQtQAsAg

- [x] Categories _(Same as products listing)_
- [x] Products listing
- [x] Product details

**NB! Test in https://github.com/Edicy/edicy_cms/pull/2035 branch.**

**Comment by kaspar-naaber** [comment]
Try to concatenate "categories" and "Products listing" to one layout.

**Comment by kaspar-naaber** [comment]
# Todo list

- [ ] Make items listing "smart" using `{{ page.level }}` or something similar.
- [ ] Allow bgpicker to save _page.data_.
- [ ] Rename layouts to something more generic.

**Comment by kaspar-naaber** [comment]
Additional TODO list:

- [ ] Add "Front page" layout support.
- [ ] List only pages that are using **"Items list"** or **"Item"** layouts.

**Comment by kaspar-naaber** [comment]
https://github.com/Edicy/edicy_cms/pull/2035 must be fixed before proceeding.
